Add example tools (#7)
* Add example tools for generating a cartesian Shepp-Logan phantom and performing simple image reconstruction in C++, Python, and MATLAB
* Add CMake FetchContent archive and checksums to Releases

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,3 +1,5 @@
+ARG DEVCONTAINER_BASE=mcr.microsoft.com/devcontainers/base:1.0.23-ubuntu-22.04
+
 #########################################################
 # file-normalizer stage
 # In order to use BuildKit remote caching, input files must have
@@ -11,6 +13,7 @@ FROM mcr.microsoft.com/oss/busybox/busybox:1.33.1 as file-normalizer
 
 COPY environment.yml \
      .devcontainer/devcontainer.bashrc  \
+     .devcontainer/matlab-r2023b.ubuntu-22.04.dependencies.txt \
      /data/
 
 RUN chmod -R 555 /data/
@@ -20,7 +23,7 @@ RUN chmod -R 555 /data/
 # Installs all dependencies and tooling for development.
 #########################################################
 
-FROM mcr.microsoft.com/vscode/devcontainers/base:0.201.8-focal AS devcontainer
+FROM ${DEVCONTAINER_BASE} AS devcontainer
 
 # Install needed packages and setup non-root user.
 ARG USERNAME="vscode"
@@ -28,17 +31,10 @@ ARG USER_UID=1000
 ARG USER_GID=$USER_UID
 ARG CONDA_GID=900
 ARG CONDA_ENVIRONMENT_NAME=mrd
-ARG VSCODE_DEV_CONTAINERS_SCRIPT_LIBRARY_VERSION=v0.229.0
 
 RUN apt-get update && apt-get install -y \
     libc6-dbg \
     && rm -rf /var/lib/apt/lists/*
-
-# Enable non-root Docker access in container
-ARG ENABLE_NONROOT_DOCKER="true"
-# Use the OSS Moby CLI instead of the licensed Docker CLI
-ARG USE_MOBY="false"
-RUN script=$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/${VSCODE_DEV_CONTAINERS_SCRIPT_LIBRARY_VERSION}/script-library/docker-debian.sh") && bash -c "$script" -- "${ENABLE_NONROOT_DOCKER}" "/var/run/docker-host.sock" "/var/run/docker.sock" "${USERNAME}" "${USE_MOBY}"
 
 # Setting the ENTRYPOINT to docker-init.sh will configure non-root access to
 # the Docker socket if "overrideCommand": false is set in devcontainer.json.
@@ -86,9 +82,12 @@ fi\n" >> /etc/bash.bashrc
 ENV CMAKE_GENERATOR=Ninja
 
 # Create a kits file for the VSCode CMake Tools extension, so you are not prompted for which kit to select whenever you open VSCode
-RUN mkdir -p /home/vscode/.local/share/CMakeTools \
-    && echo '[{"name":"GCC","compilers":{"C":"/opt/conda/envs/mrd/bin/x86_64-conda_cos6-linux-gnu-gcc","CXX":"/opt/conda/envs/mrd/bin/x86_64-conda_cos6-linux-gnu-g++"}}]' > /home/vscode/.local/share/CMakeTools/cmake-tools-kits.json \
+RUN . /opt/conda/etc/profile.d/conda.sh \
+    && conda activate /opt/conda/envs/mrd \
+    && mkdir -p /home/vscode/.local/share/CMakeTools \
+    && echo "[{\"name\":\"Conda\",\"compilers\":{\"C\":\"$GCC\",\"CXX\":\"$GXX\"}}]" > /home/vscode/.local/share/CMakeTools/cmake-tools-kits.json \
     && chown vscode:conda /home/vscode/.local/share/CMakeTools/cmake-tools-kits.json
+
 
 # Install the yardl tool
 ARG YARDL_VERSION=0.5.0
@@ -96,3 +95,61 @@ RUN wget --quiet "https://github.com/microsoft/yardl/releases/download/v${YARDL_
     && tar -xzf "yardl_${YARDL_VERSION}_linux_x86_64.tar.gz" \
     && mv yardl "/opt/conda/envs/${CONDA_ENVIRONMENT_NAME}/bin/" \
     && rm "yardl_${YARDL_VERSION}_linux_x86_64.tar.gz"
+
+
+#########################################################
+# Install Matlab
+#   Based on mathworks/{matlab-deps:r2023b,matlab:r2023b}
+#
+# Configure the Matlab License Server to use Matlab within the devcontainer (including VSCode extensions):
+#   In your HOST environment, export the environment variable MATLAB_LICENSE_FILE, e.g.
+#       export MATLAB_LICENSE_FILE=/mnt/c/Users/username/Documents/MATLAB/license.lic
+#########################################################
+
+ENV DEBIAN_FRONTEND="noninteractive" TZ="Etc/UTC"
+
+COPY --from=file-normalizer /data/matlab-r2023b.ubuntu-22.04.dependencies.txt /tmp/matlab-dependencies.txt
+
+RUN export DEBIAN_FRONTEND=noninteractive \
+    && apt-get update \
+    && apt-get install --no-install-recommends --yes \
+    `cat /tmp/matlab-dependencies.txt` \
+    wget \
+    unzip \
+    ca-certificates \
+    && apt-get clean \
+    && apt-get -y autoremove \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN [ -d /usr/share/X11/xkb ] || mkdir -p /usr/share/X11/xkb
+
+ARG MATLAB_RELEASE=r2023b
+ARG MATLAB_PRODUCT_LIST="MATLAB"
+ARG MATLAB_INSTALL_LOCATION="/opt/matlab/${MATLAB_RELEASE}"
+ARG LICENSE_SERVER=
+
+RUN adduser --shell /bin/bash --disabled-password --gecos "" matlab \
+    && echo "matlab ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/matlab \
+    && chmod 0440 /etc/sudoers.d/matlab
+
+USER matlab
+WORKDIR /home/matlab
+
+ENV MLM_LICENSE_FILE=${LICENSE_SERVER}
+
+RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
+    && chmod +x mpm \
+    && sudo HOME=${HOME} ./mpm install \
+    --release=${MATLAB_RELEASE} \
+    --destination=${MATLAB_INSTALL_LOCATION} \
+    --products ${MATLAB_PRODUCT_LIST} \
+    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
+    && sudo rm -f mpm /tmp/mathworks_root.log \
+    && sudo ln -s ${MATLAB_INSTALL_LOCATION}/bin/matlab /usr/local/bin/matlab \
+    && sudo ln -s ${MATLAB_INSTALL_LOCATION} /opt/matlab/latest \
+    && sudo mkdir -p ${MATLAB_INSTALL_LOCATION}/licenses
+
+# Install workaround run-matlab-command script to unify local and CI invocations of `matlab -batch`
+# See https://github.com/matlab-actions/run-command/issues/53
+RUN sudo wget -O /usr/local/bin/run-matlab-command https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/glnxa64/run-matlab-command \
+    && sudo chmod +x /usr/local/bin/run-matlab-command
